# Generated by Django 5.1 on 2024-08-29 18:45

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter class name', max_length=200, unique=True, verbose_name='Class Name')),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(default='courses/course_avatar.jpg', upload_to=courses.models.get_image_upload_path)),
                ('date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
