# Generated by Django 5.1 on 2024-08-24 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('image', models.ImageField(default='profile_avatar.jpg', upload_to='trainer/%Y/%m/%d/')),
                ('facebook', models.URLField(blank=True, default='https://www.facebook.com/', max_length=100, null=True)),
                ('twitter', models.URLField(blank=True, default='https://twitter.com/', max_length=100, null=True)),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/', max_length=100, null=True)),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profession')),
            ],
        ),
    ]
