# Generated by Django 5.1 on 2024-08-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='profession',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
    ]
