# Generated by Django 5.1 on 2024-08-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_trainer_category_trainer_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='started_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
