# Generated by Django 5.1 on 2024-08-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_trainer_started_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='started_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
