# Generated by Django 5.1 on 2024-08-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_trainer_started_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='category',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Fitness & Gym', 'Fitness & Gym'), ('Gymnastics', 'Gymnastics'), ('Running', 'Running')], default='Yoga', help_text='Select the category of the product.', max_length=25),
        ),
    ]
