# Generated by Django 5.1 on 2024-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_trainer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='profession',
            field=models.CharField(choices=[('Yoga Master', 'Yoga Master'), ('Personal trainer', 'Personal Trainer'), ('Boxer', 'Boxer'), ('Business Analytic', 'Business Analytic'), ('Other', 'Other')], default='Yoga Master', help_text='Select the one profession from these.', max_length=25),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='difficulty_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', help_text='Select the difficulty level of the task.', max_length=25),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='intensity_level',
            field=models.CharField(choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3')], default='level_2', help_text='Select the intensity level of the exercise.', max_length=25),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='time_of_day',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='morning', help_text='Select the time of day for this schedule.', max_length=25),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='yoga_style',
            field=models.CharField(choices=[('Morning Yoga', 'Morning Yoga'), ('Vinyasa Yoga', 'Vinyasa Yoga'), ('Acro Yoga', 'Acro Yoga')], default='morning', help_text='Select the style of yoga for this session.', max_length=25),
        ),
    ]
