# Generated by Django 5.1 on 2024-08-25 12:50

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_trainer_profession_alter_trainer_difficulty_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40)),
                ('logo', models.ImageField(default='review_avatar.png', upload_to=home.models.get_review_upload_path)),
                ('content', models.TextField(max_length=250)),
                ('desginer', models.CharField(max_length=40)),
            ],
        ),
    ]
