# Generated by Django 5.1 on 2024-08-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='main_category',
            field=models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Fitness', 'Fitness'), ('Mindfulness', 'Mindfulness')], default='Yoga', help_text='Select the main category of the move.', max_length=25),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='category',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Fitness & Gym', 'Fitness & Gym'), ('Gymnastics', 'Gymnastics'), ('Running', 'Running')], default='Yoga', help_text='Select the category of the move.', max_length=25),
        ),
    ]
