# Generated by Django 5.1 on 2024-08-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_trainer_main_category_alter_trainer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='main_category',
            field=models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Fitness', 'Fitness'), ('Mindfulness', 'Mindfulness')], default='Lifestyle', help_text='Select the main category of the move.', max_length=25),
        ),
    ]
